server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  logging:
    level:
      org.springframework.security: DEBUG

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER:auth-backend}
  access-ttl: ${JWT_ACCESS_TTL:3600}
  refresh-ttl: ${JWT_REFRESH_TTL:86400}
  refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
  cookie-secure: ${JWT_COOKIE_SECURE:true}
  cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
  cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
  cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}

app:
  cors:
    frontend-url: http://localhost:5173
  auth:
    frontend:
      success-redirect: http://localhost:5173/auth/success
      failure-redirect: http://localhost:5173/auth/failure



